### ISSUE TITLE
Error at Navigation menu

### ISSUE THREAD

**Issue by sagarad931** [instantcommerce/shopify-headless-theme#27]
Navigation menu don't appear on frontend

**Comment by leeuwis** [comment]
Hey @sagarad931, can you give a bit more context for your issue or what you are trying to do?

This repo in not responsible for any navigation menu in the frontend, so you might be looking in the wrong place.

**Comment by sagarad931** [comment]
@leeuwis well I have created the navigation menu as Header menu and Footer menu on shopify account but it don't appear on my frontend app. Then I contact with shopify support team and they suggest me that the problem lies on the shopify-headless-theme-master .

So here I am, to make sure my shopify-headless-theme-master has any problem or not.  Also when I try to customize my theme it always show "Redirecting..." only.

**Comment by leeuwis** [comment]
Hey @sagarad931, it's a "headless" theme since your frontend code doesn't live in your Shopify theme. The sole purpose of this theme is to redirect to your headless storefront outside of Shopify. E.g. if you want to make use of Shopify their Hydrogen storefront setup: https://github.com/Shopify/hydrogen
