### ISSUE TITLE
Supporting domain aliases

### ISSUE THREAD

**Issue by MaSchVam** [instantcommerce/shopify-headless-theme#4]
Hello,

This theme is really a great idea. I just tried it out on a store that uses a domain alias:

`normalsetup.myshopify.com —> custom.customdomain.com`

And I see that clicking the logo in the checkout causes an infinite redirect loop. Any way around this behavior, with this theme?

**Comment by leeuwis** [comment]
Hey @MaSchVam, that should definitely be possible! After installing the headless theme, did you define the "Base URL" in the theme settings? This should look like this:

<img width="473" alt="Screenshot 2022-10-12 at 14 42 51" src="https://user-images.githubusercontent.com/19343479/195345481-40930157-435d-4419-8ec6-084fc41f21ce.png">

**Comment by MaSchVam** [comment]
@leeuwis ,

Instead of getting the shop url on line 28 in theme.liquid, I now just grab `window.location.href.` This should cover this usecase?

**Comment by leeuwis** [comment]
@MaSchVam I've opened a PR with a fix, let me know if this fixes the issue for you!

It's indeed fixed by changing the value on line 28 in `theme.liquid`, but I ended up using `window.location.hostname` instead of the `window.location.href`. If `window.location.href` would be used, all traffic will always be redirect to the home url of your storefront, but the path should also stay intact so `https://example.myshopify.com/products/slug-x` also gets redirected to `https://example.com/products/slug-x`.
